/**
 * Known Workday tenant -> { pod number, career site slugs }.
 *
 * discoverConfig() normally guesses: it walks every pod in WD_NUMBERS fetching robots.txt and
 * scrapes the site slug out of a Sitemap: line. That fails whenever a tenant serves no
 * robots.txt, or serves one with no Sitemap line — and the company is then written off with
 * "could not discover config", even though its board is perfectly healthy.
 *
 * Measured 2026-08-10: 47 of the 245 tenants on this list were sitting inactive/failed for
 * exactly that reason, and probing them with the coordinates below reached 46 boards holding
 * **46,784 jobs** — cvshealth 18,998, tjx 9,952, bah 2,000, leidos 1,963, blueorigin 1,424.
 * Guessing is a fallback, not the primary source, so anything known goes here.
 *
 * A tenant can run several career sites (relx runs four); jobs are fetched from each and merged,
 * since a posting usually appears on only one of them.
 *
 * Adding a tenant: set status=active, last_synced_at=NULL on its companies row so the crawler
 * re-claims it, otherwise the entry sits here unused.
 */
const WORKDAY_SITES = {
  abglobal: { wdNum: 1, sites: ["alliancebernsteincareers"] },
  accenture: { wdNum: 103, sites: ["AccentureCareers"] },
  adobe: { wdNum: 5, sites: ["external_experienced"] },
  aero: { wdNum: 5, sites: ["External"] },
  ag: { wdNum: 3, sites: ["Airbus"] },
  agilent: { wdNum: 5, sites: ["Agilent_Careers"] },
  aig: { wdNum: 1, sites: ["aig"] },
  airproducts: { wdNum: 5, sites: ["AP0001"] },
  ais: { wdNum: 3, sites: ["Careers"] },
  akumincorp: { wdNum: 5, sites: ["akumincareers"] },
  allegion: { wdNum: 5, sites: ["careers"] },
  allegromicro: { wdNum: 5, sites: ["AllegroCareers"] },
  alliance: { wdNum: 3, sites: ["nissanjobs"] },
  alliancewd: { wdNum: 3, sites: ["renault-group-careers"] },
  allstate: { wdNum: 5, sites: ["allstate_careers"] },
  altera: { wdNum: 1, sites: ["Altera"] },
  amgen: { wdNum: 1, sites: ["Careers"] },
  amh: { wdNum: 12, sites: ["External_Careers"] },
  analogdevices: { wdNum: 1, sites: ["External"] },
  archgroup: { wdNum: 1, sites: ["careers"] },
  aritzia: { wdNum: 3, sites: ["External"] },
  aspendental: { wdNum: 1, sites: ["Careers_The_Aspen_Group"] },
  assetmark: { wdNum: 5, sites: ["AssetMark_Careers"] },
  att: { wdNum: 1, sites: ["ATTGeneral"] },
  autodesk: { wdNum: 1, sites: ["Ext"] },
  aviva: { wdNum: 1, sites: ["External"] },
  awg: { wdNum: 3, sites: ["AW", "PS"] },
  bah: { wdNum: 1, sites: ["BAH_Jobs"] },
  baltimorecity: { wdNum: 1, sites: ["External"] },
  barclays: { wdNum: 3, sites: ["External_Career_Site_Barclays"] },
  bcbsa: { wdNum: 1, sites: ["Careers"] },
  bdo: { wdNum: 3, sites: ["BDO"] },
  beigene: { wdNum: 5, sites: ["BeiGene"] },
  bloomberg: { wdNum: 1, sites: ["Bloombergindustrygroup_External_Career_Site"] },
  blueorigin: { wdNum: 5, sites: ["BlueOrigin"] },
  bristolmyerssquibb: { wdNum: 5, sites: ["BMS"] },
  broadridge: { wdNum: 5, sites: ["Careers"] },
  brookfield: { wdNum: 5, sites: ["brookfieldproperties"] },
  caa: { wdNum: 1, sites: ["Careers"] },
  cadence: { wdNum: 1, sites: ["External_Careers"] },
  calyx: { wdNum: 1, sites: ["Perceptive"] },
  capitalone: { wdNum: 12, sites: ["Capital_One"] },
  capri: { wdNum: 1, sites: ["Michael_Kors"] },
  carrier: { wdNum: 5, sites: ["jobs"] },
  castandcrew: { wdNum: 503, sites: ["castandcrew"] },
  cba: { wdNum: 3, sites: ["CommBank_Careers"] },
  ceritypartners: { wdNum: 12, sites: ["ceritypartnerscareers"] },
  ci: { wdNum: 3, sites: ["CI_FINANCIAL_EXTERNAL_CAREER-SITE"] },
  cibc: { wdNum: 3, sites: ["search"] },
  ciena: { wdNum: 5, sites: ["Careers"] },
  cigna: { wdNum: 5, sites: ["cignacareers"] },
  cisco: { wdNum: 5, sites: ["Cisco_Careers"] },
  cisive: { wdNum: 108, sites: ["Cisive"] },
  clarioclinical: { wdNum: 1, sites: ["clarioclinical_careers"] },
  claytonhomes: { wdNum: 1, sites: ["ClaytonCareers"] },
  clio: { wdNum: 3, sites: ["ClioCareerSite"] },
  cloudera: { wdNum: 5, sites: ["External_Career"] },
  cloudflight: { wdNum: 103, sites: ["external_career_site"] },
  comcast: { wdNum: 5, sites: ["Comcast_Careers"] },
  convatec: { wdNum: 1, sites: ["ConvaTec"] },
  copart: { wdNum: 12, sites: ["Copart"] },
  cotality: { wdNum: 115, sites: ["Global"] },
  crowdstrike: { wdNum: 5, sites: ["crowdstrikecareers"] },
  cvshealth: { wdNum: 1, sites: ["cvs_health_careers"] },
  demegroup: { wdNum: 3, sites: ["careers_external"] },
  dentsuaegis: { wdNum: 3, sites: ["DAN_GLOBAL"] },
  dexcom: { wdNum: 1, sites: ["dexcom"] },
  diconium: { wdNum: 3, sites: ["diconium"] },
  disney: { wdNum: 5, sites: ["disneycareer"] },
  dlapiper: { wdNum: 1, sites: ["dlapiper"] },
  dollartree: { wdNum: 5, sites: ["dollartreeus"] },
  edenpeople: { wdNum: 3, sites: ["Edenred_Careers"] },
  expedia: { wdNum: 108, sites: ["search"] },
  fico: { wdNum: 1, sites: ["External"] },
  fil: { wdNum: 3, sites: ["001"] },
  firstquality: { wdNum: 5, sites: ["FIRSTQUALITY"] },
  flextronics: { wdNum: 1, sites: ["Careers"] },
  fractal: { wdNum: 1, sites: ["Careers"] },
  freudenberg: { wdNum: 3, sites: ["freudenberg-group"] },
  frostbank: { wdNum: 5, sites: ["External"] },
  gdit: { wdNum: 5, sites: ["External_Career_Site"] },
  geico: { wdNum: 1, sites: ["External"] },
  genesys: { wdNum: 1, sites: ["Genesys"] },
  genpact: { wdNum: 108, sites: ["External_Careers"] },
  genpt: { wdNum: 1, sites: ["Careers"] },
  gilead: { wdNum: 1, sites: ["gileadcareers"] },
  globalfoundries: { wdNum: 1, sites: ["External"] },
  globalhr: { wdNum: 5, sites: ["rec_rtx_ext_gateway"] },
  globe: { wdNum: 3, sites: ["glb_careers"] },
  gnw: { wdNum: 1, sites: ["GNW"] },
  guidehouse: { wdNum: 1, sites: ["External"] },
  healthcare: { wdNum: 1, sites: ["Search"] },
  hedgeserv: { wdNum: 1, sites: ["HedgeServ"] },
  heidrick: { wdNum: 1, sites: ["heidrickandstruggles"] },
  hillenbrand: { wdNum: 3, sites: ["Global"] },
  holmesmurphy: { wdNum: 1, sites: ["HolmesMurphyCareers"] },
  hpe: { wdNum: 5, sites: ["Jobsathpe", "wfmathpe"] },
  humana: { wdNum: 5, sites: ["Humana_External_Career_Site"] },
  huntsman: { wdNum: 1, sites: ["Huntsman"] },
  huron: { wdNum: 1, sites: ["huroncareers"] },
  icf: { wdNum: 5, sites: ["ICFExternal_Career_Site"] },
  iff: { wdNum: 5, sites: ["IFF_Careers"] },
  illumina: { wdNum: 1, sites: ["illumina-careers"] },
  infobip: { wdNum: 3, sites: ["InfobipCareers"] },
  insulet: { wdNum: 5, sites: ["insuletcareers"] },
  integritymarketing: { wdNum: 1, sites: ["Integrity"] },
  intel: { wdNum: 1, sites: ["External"] },
  invesco: { wdNum: 1, sites: ["IVZ"] },
  investpsp: { wdNum: 3, sites: ["psp_careers"] },
  iress: { wdNum: 3, sites: ["IRESS_EXTERNAL"] },
  irvingoil: { wdNum: 3, sites: ["IOL_Careers_Primary"] },
  jll: { wdNum: 1, sites: ["jllcareers"] },
  juliusbaer: { wdNum: 3, sites: ["JB_Career_Site_TAD_External"] },
  justfab: { wdNum: 1, sites: ["fabletics"] },
  kimcorealty: { wdNum: 503, sites: ["KimcoCareers"] },
  kla: { wdNum: 1, sites: ["Search"] },
  kone: { wdNum: 3, sites: ["Careers"] },
  kyndryl: { wdNum: 5, sites: ["KyndrylProfessionalCareers"] },
  lbg: { wdNum: 3, sites: ["Lloyds_Technology_Centre"] },
  leidos: { wdNum: 5, sites: ["External"] },
  lennar: { wdNum: 1, sites: ["lennar_jobs"] },
  leonardocompany: { wdNum: 3, sites: ["LeonardoCareerSite"] },
  lindenwood: { wdNum: 1, sites: ["CareerOpportunities"] },
  lithia: { wdNum: 5, sites: ["LithiaCareers"] },
  livenation: { wdNum: 503, sites: ["LNExternalSite"] },
  logicalis: { wdNum: 3, sites: ["iZenoCareers"] },
  lseg: { wdNum: 3, sites: ["Careers"] },
  luriechildrens: { wdNum: 1, sites: ["externalportal"] },
  magna: { wdNum: 3, sites: ["magna"] },
  magnitudesoftware: { wdNum: 1, sites: ["External"] },
  marmon: { wdNum: 501, sites: ["Marmon_Careers"] },
  marvell: { wdNum: 1, sites: ["MarvellCareers"] },
  mavericktransportation: { wdNum: 108, sites: ["Maverick-Transportation"] },
  mckesson: { wdNum: 3, sites: ["External_Careers"] },
  medtronic: { wdNum: 1, sites: ["MedtronicCareers"] },
  mfs: { wdNum: 1, sites: ["MFS-Careers"] },
  mgic: { wdNum: 5, sites: ["mgic"] },
  mgpru: { wdNum: 3, sites: ["mandgprudential"] },
  minnstate: { wdNum: 115, sites: ["Minnesota_State_Careers"] },
  modmed: { wdNum: 501, sites: ["ModMed12"] },
  monnoyeur: { wdNum: 103, sites: ["Monnoyeur"] },
  mpc: { wdNum: 1, sites: ["MPCCareers"] },
  mwe: { wdNum: 5, sites: ["mwe_careers"] },
  nasdaq: { wdNum: 1, sites: ["Global_External_Site"] },
  nclh: { wdNum: 108, sites: ["NCL_Shoreside_Careers"] },
  nelnet: { wdNum: 1, sites: ["mynelnet"] },
  netflix: { wdNum: 108, sites: ["Netflix"] },
  newday: { wdNum: 3, sites: ["NewDay"] },
  nexperia: { wdNum: 3, sites: ["careers"] },
  ntrs: { wdNum: 1, sites: ["northerntrust"] },
  nvidia: { wdNum: 5, sites: ["NVIDIAExternalCareerSite"] },
  nxp: { wdNum: 3, sites: ["careers"] },
  ocbc: { wdNum: 102, sites: ["External"] },
  omnissa: { wdNum: 501, sites: ["omnissa_external_career_site"] },
  osfibsif: { wdNum: 10, sites: ["OSFI"] },
  "osv-cci": { wdNum: 1, sites: ["CCICareers"] },
  ouryahoo: { wdNum: 5, sites: ["careers"] },
  oxy: { wdNum: 5, sites: ["corporate"] },
  pacificlife: { wdNum: 1, sites: ["PacificLifeCareers"] },
  packsize: { wdNum: 108, sites: ["Packsize_Careers"] },
  parexel: { wdNum: 1, sites: ["Parexel_External_Careers"] },
  paulhastings: { wdNum: 1, sites: ["PH-Staff"] },
  paypal: { wdNum: 1, sites: ["jobs"] },
  payward: { wdNum: 1, sites: ["Kraken_Careers"] },
  petermillarllc: { wdNum: 12, sites: ["PMI"] },
  petersonholding: { wdNum: 1, sites: ["PetersonJobs"] },
  prescryptive: { wdNum: 503, sites: ["Prescryptive_Health_External"] },
  primetherapeutics: { wdNum: 1, sites: ["PrimeTherapeuticsCareers"] },
  prodege: { wdNum: 108, sites: ["Prodege_Careers"] },
  proofpoint: { wdNum: 5, sites: ["ProofpointCareers"] },
  pru: { wdNum: 5, sites: ["Careers"] },
  prudential: { wdNum: 3, sites: ["prudential"] },
  psu: { wdNum: 1, sites: ["PSU_Staff"] },
  ptc: { wdNum: 1, sites: ["PTC"] },
  pwc: { wdNum: 3, sites: ["Global_Campus_Careers", "US_Experienced_Careers"] },
  qtsdatacenters: { wdNum: 5, sites: ["qts"] },
  qualys: { wdNum: 5, sites: ["Careers"] },
  quantiphi: { wdNum: 1, sites: ["Careers_at_Quantiphi"] },
  razer: { wdNum: 3, sites: ["Careers"] },
  relx: { wdNum: 3, sites: ["relx", "LexisNexisLegal", "ReedExhibitions", "ElsevierJobs"] },
  rochester: { wdNum: 5, sites: ["UR_Staff"] },
  rockwoolgroup: { wdNum: 3, sites: ["ROCKWOOL"] },
  rollsroyce: { wdNum: 3, sites: ["professional"] },
  ryancompanies: { wdNum: 5, sites: ["ryancompanies"] },
  ryder: { wdNum: 5, sites: ["rydercareers"] },
  rytbank: { wdNum: 3, sites: ["External_Career"] },
  salesforce: { wdNum: 12, sites: ["External_Career_Site"] },
  sands: { wdNum: 1, sites: ["sands_careers"] },
  sandvik: { wdNum: 3, sites: ["Sandvik_Internal_for_nonWD_employees"] },
  santander: { wdNum: 3, sites: ["SantanderCareers"] },
  sbdinc: { wdNum: 1, sites: ["Stanley_Black_Decker_Career_Site"] },
  sec: { wdNum: 3, sites: ["Samsung_Careers"] },
  sentara: { wdNum: 1, sites: ["SCS"] },
  servco: { wdNum: 5, sites: ["Servco_Careers"] },
  servicetitan: { wdNum: 1, sites: ["ServiceTitan"] },
  shi: { wdNum: 12, sites: ["shicareers"] },
  simcorp: { wdNum: 3, sites: ["SimCorp_Jobs"] },
  smithnephew: { wdNum: 5, sites: ["External"] },
  specialized: { wdNum: 5, sites: ["Specialized_External_Career_Site"] },
  statestreet: { wdNum: 1, sites: ["Global"] },
  stord: { wdNum: 503, sites: ["Stord_External_Career"] },
  sunlife: { wdNum: 3, sites: ["Experienced-Jobs"] },
  swbc: { wdNum: 1, sites: ["InformationTechnology"] },
  tbc: { wdNum: 12, sites: ["lyriccareers"] },
  td: { wdNum: 3, sites: ["TD_Bank_Careers"] },
  thehartford: { wdNum: 5, sites: ["Careers_External", "Careers_Restricted"] },
  thomsonreuters: { wdNum: 5, sites: ["External_Career_Site"] },
  tjx: { wdNum: 1, sites: ["TJX_EXTERNAL"] },
  tmx: { wdNum: 3, sites: ["TMX_Careers"] },
  tp: { wdNum: 107, sites: ["TP-ICAP"] },
  trafigura: { wdNum: 3, sites: ["TrafiguraCareerSite"] },
  transamerica: { wdNum: 5, sites: ["US"] },
  transunion: { wdNum: 5, sites: ["TransUnion"] },
  travelers: { wdNum: 5, sites: ["External"] },
  trimble: { wdNum: 1, sites: ["TrimbleCareers"] },
  troweprice: { wdNum: 5, sites: ["TRowePrice"] },
  tti: { wdNum: 1, sites: ["milwaaukeemxtalento"] },
  turo: { wdNum: 12, sites: ["Turo_careers"] },
  tysonfoods: { wdNum: 5, sites: ["TSN"] },
  ulse: { wdNum: 5, sites: ["ulsecareers"] },
  umd: { wdNum: 1, sites: ["UMCP"] },
  umusic: { wdNum: 5, sites: ["UMGUS", "UMGUK"] },
  unhcr: { wdNum: 3, sites: ["External"] },
  unisys: { wdNum: 5, sites: ["External"] },
  univision: { wdNum: 1, sites: ["External"] },
  unum: { wdNum: 1, sites: ["External"] },
  uobgroup: { wdNum: 3, sites: ["UOBExternal"] },
  utaustin: { wdNum: 1, sites: ["UTstaff"] },
  valmet: { wdNum: 103, sites: ["External"] },
  vantagedc: { wdNum: 1, sites: ["Vantage"] },
  velera: { wdNum: 5, sites: ["VeleraCareers"] },
  visa: { wdNum: 5, sites: ["Visa"] },
  walkerdunlop: { wdNum: 1, sites: ["WD"] },
  washpost: { wdNum: 5, sites: ["washingtonpostcareers"] },
  waystar: { wdNum: 1, sites: ["Waystar"] },
  wellington: { wdNum: 5, sites: ["eFC"] },
  wellsky: { wdNum: 1, sites: ["WellSkyCareers"] },
  westernalliancebank: { wdNum: 5, sites: ["WAB"] },
  wmeimg: { wdNum: 1, sites: ["WME", "WMEGRP"] },
  workday: { wdNum: 5, sites: ["Workday"] },
  workiva: { wdNum: 503, sites: ["careers"] },
  worldvision: { wdNum: 1, sites: ["WorldVisionInternational"] },
  yeticoolers: { wdNum: 5, sites: ["YETI"] },
  zayo: { wdNum: 1, sites: ["zayo_careers"] },
  zieglercat: { wdNum: 1, sites: ["zieglercat"] },
  zillow: { wdNum: 5, sites: ["Zillow_Group_External"] },
  zoetis: { wdNum: 5, sites: ["zoetis"] },
  zuehlke: { wdNum: 3, sites: ["Zuhlke-Careers"] },
};

module.exports = { WORKDAY_SITES };
