/**
 * Comprehensive cross-industry role vocabulary for the resumly bulk drain.
 * ~28 industries. ALL_ROLES is the flattened, de-duplicated list the drain iterates.
 */
const ROLES_BY_INDUSTRY = {
  "Technology, Software & Data": [
    "Software Engineer", "Frontend Developer", "Backend Developer", "Full Stack Developer",
    "Data Engineer", "Data Scientist", "Machine Learning Engineer", "DevOps Engineer",
    "Cloud Engineer", "Site Reliability Engineer", "Product Manager", "Product Designer",
    "UX Designer", "UI Designer", "iOS Developer", "Android Developer", "Mobile Developer",
    "QA Engineer", "Security Engineer", "Platform Engineer", "Infrastructure Engineer",
    "Solutions Engineer", "Sales Engineer", "Technical Program Manager", "Engineering Manager",
    "Data Analyst", "Business Analyst", "Cybersecurity Analyst", "Network Engineer",
    "Systems Engineer", "Database Administrator", "AI Engineer", "Blockchain Developer",
    "Embedded Systems Engineer", "Customer Success Manager", "Technical Writer", "Scrum Master",
    "Java Developer", "Python Developer", "React Developer", "Node.js Developer",
    "Golang Developer", "Rust Developer", ".NET Developer", "PHP Developer", "Ruby Developer",
    "Scala Developer", "Kotlin Developer", "Swift Developer", "Account Executive",
    "Account Manager", "Customer Support", "Marketing Manager", "Growth Manager",
    "Content Strategist", "Recruiter", "HR Manager", "People Operations", "Finance Manager",
    "Financial Analyst", "Controller", "Project Manager", "Operations Manager", "Chief of Staff",
    "Senior Software Engineer", "Staff Software Engineer", "Principal Software Engineer",
    "Lead Software Engineer", "Software Engineering Manager", "Software Development Engineer",
    "Software Architect", "Backend Engineer", "Frontend Engineer", "Full Stack Engineer",
    "Go Developer", "Solutions Architect", "Cloud Architect", "Test Engineer",
    "Automation Engineer", "Mobile Engineer", "React Native Developer", "Flutter Developer",
    "Analytics Engineer", "Business Intelligence Analyst", "Research Scientist",
    "Senior Product Manager", "Technical Product Manager", "UX Researcher",
    "Senior DevOps Engineer", "Build Engineer", "Release Engineer", "Kubernetes Engineer",
    "Content Writer", "Program Manager", "Delivery Manager", "Sales Development Representative",
    "Business Development Representative", "Growth Marketing Manager", "SEO Specialist",
    "Demand Generation Manager", "Customer Support Specialist", "Technical Support Engineer",
    "Technical Account Manager", "Director of Engineering", "VP of Engineering",
    "Chief Technology Officer", "Director of Product", "Head of Product",
    "Business Operations Manager", "Technical Recruiter", "People Operations Manager",
    "Accountant", "Cybersecurity Manager", "Compliance", "GRC", "Smart Contract Developer",
    "Web3 Developer", "Developer Advocate", "Developer Relations Engineer", "Supply Chain Manager",
    "Procurement Manager", "Logistics Manager", "Healthcare Software Engineer",
    "Clinical Data Analyst", "Game Developer", "Game Designer", "Unity Developer",
  ],
  "Supply Chain & Logistics": [
    "Buyer", "Category Manager", "Commodity Manager", "Continuous Improvement Manager",
    "Customer Service Representative", "Customs Broker", "Customs Compliance Specialist",
    "Demand Planner", "Demand Planning Manager", "Dispatcher", "Distribution Center Manager",
    "Distribution Manager", "Distribution Supervisor", "Fleet Manager", "Forklift Operator",
    "Freight Broker", "Fulfillment Manager", "Fulfillment Operations Manager",
    "Import Export Coordinator", "Industrial Engineer", "Inventory Analyst", "Inventory Clerk",
    "Inventory Control Specialist", "Inventory Manager", "Last Mile Delivery Manager",
    "Load Coordinator", "Logistics Analyst", "Logistics Coordinator", "Logistics Engineer",
    "Logistics Specialist", "Manufacturing Engineer", "Master Scheduler", "Material Handler",
    "Materials Manager", "Materials Planner", "Operations Analyst", "Operations Coordinator",
    "Order Fulfillment Specialist", "Order Picker", "Packer", "Process Engineer",
    "Procurement Analyst", "Procurement Specialist", "Production Planner", "Production Scheduler",
    "Purchasing Agent", "Purchasing Manager", "Returns Specialist",
    "Sales and Operations Planning Manager", "Shipping and Receiving Clerk", "Sourcing Specialist",
    "Strategic Sourcing Manager", "Supplier Quality Engineer", "Supply Chain Analyst",
    "Supply Chain Coordinator", "Supply Chain Director", "Supply Chain Engineer",
    "Supply Chain Planner", "Supply Chain Specialist", "Supply Planner",
    "Trade Compliance Manager", "Transportation Analyst", "Transportation Coordinator",
    "Transportation Manager", "Transportation Supervisor", "Vendor Manager", "Warehouse Associate",
    "Warehouse Lead", "Warehouse Manager", "Warehouse Operations Manager", "Warehouse Supervisor",
  ],
  "Aerospace & Defense": [
    "A&P Mechanic", "Acoustics Engineer", "Aerodynamics Engineer", "Aeronautical Engineer",
    "Aerospace Engineer", "Aircraft Maintenance Technician", "Aircraft Mechanic",
    "Airworthiness Engineer", "Antenna Engineer", "Assembly Technician", "Astronautical Engineer",
    "Avionics Engineer", "Avionics Technician", "CAD Designer", "Calibration Technician",
    "Certification Engineer", "CNC Machinist", "Composites Engineer",
    "Configuration Management Specialist", "Contracts Administrator", "Cost Analyst",
    "Counterintelligence Analyst", "Director of Operations", "Drafter", "Drone Pilot",
    "Earned Value Management Analyst", "Electrical Engineer", "Electro-Optical Engineer",
    "Electronics Technician", "Environmental Test Engineer", "Facility Security Officer",
    "Field Service Engineer", "Field Service Technician", "Flight Test Engineer",
    "Flight Test Pilot", "FPGA Engineer", "GNC Engineer", "Ground Systems Engineer",
    "Guidance Navigation and Control Engineer", "Hardware Engineer", "Human Factors Engineer",
    "Industrial Security Specialist", "Integration and Test Engineer", "Intelligence Analyst",
    "Launch Engineer", "Liaison Engineer", "Machinist", "Manufacturing Manager",
    "Manufacturing Technician", "Material Planner", "Materials Engineer", "Mechanical Designer",
    "Mechanical Engineer", "Mission Assurance Engineer", "Mission Operations Engineer",
    "Mission Systems Engineer", "Model-Based Systems Engineer", "Optical Engineer",
    "Ordnance Technician", "Payload Engineer", "Production Engineer", "Production Supervisor",
    "Project Engineer", "Proposal Manager", "Propulsion Engineer", "Quality Assurance Inspector",
    "Quality Engineer", "Quality Manager", "Radar Systems Engineer", "Reliability Engineer",
    "RF Engineer", "Rocket Engine Technician", "Satellite Systems Engineer",
    "Sheet Metal Mechanic", "Software Quality Engineer", "Spacecraft Engineer", "Stress Engineer",
    "Structural Analysis Engineer", "Subcontracts Administrator", "Systems Integration Manager",
    "Systems Safety Engineer", "Telemetry Engineer", "Test Pilot", "Thermal Engineer",
    "Tooling Engineer", "UAV Operator", "Vibration Engineer", "Weapons Systems Engineer",
  ],
  "Manufacturing & Industrial Operations": [
    "Assembler", "Assembly Line Worker", "Assembly Supervisor", "CNC Programmer",
    "Continuous Improvement Engineer", "Controls Engineer", "Director of Manufacturing",
    "EHS Specialist", "Environmental Health and Safety Manager", "Extrusion Operator",
    "Fabricator", "Fulfillment Associate", "Grinder", "Industrial Maintenance Technician",
    "Injection Molding Technician", "Lean Manufacturing Engineer", "Line Lead", "Machine Operator",
    "Maintenance Manager", "Maintenance Planner", "Maintenance Technician",
    "Manufacturing Director", "Manufacturing Operations Manager", "Manufacturing Supervisor",
    "Mold Maker", "Packaging Engineer", "Plant Controller", "Plant Manager", "Press Operator",
    "Process Technician", "Production Associate", "Production Control Specialist",
    "Production Lead", "Production Manager", "Production Operator", "Production Technician",
    "Production Worker", "Quality Assurance Engineer", "Quality Assurance Specialist",
    "Quality Auditor", "Quality Control Coordinator", "Quality Engineering Manager",
    "Quality Inspector", "Quality Technician", "Safety Coordinator", "Shift Supervisor",
    "Sourcing Manager", "Stamping Operator", "Supplier Development Engineer", "Tool and Die Maker",
    "Tool Crib Attendant", "Tooling Technician", "Validation Engineer", "Welder",
  ],
  "Mechanical, Electrical & Civil Engineering (non-software)": [
    "Applications Engineer", "CAD Technician", "Civil Designer", "Civil Engineer",
    "Commissioning Engineer", "Construction Engineer", "Construction Manager",
    "Construction Superintendent", "Design Drafter", "Electrical Design Engineer",
    "Electrical Designer", "Electrical Technician", "Electronics Engineer",
    "Engineering Technician", "Environmental Engineer", "Estimating Engineer", "Estimator",
    "Field Engineer", "Geotechnical Engineer", "HVAC Engineer", "Instrumentation Technician",
    "Land Surveyor", "Maintenance Engineer", "Mechanical Design Engineer", "Mechanical Technician",
    "PCB Design Engineer", "Piping Engineer", "Plant Engineer", "Power Systems Engineer",
    "Site Engineer", "Structural Engineer", "Survey Technician", "Test Technician",
    "Transportation Engineer", "Water Resources Engineer", "Welding Engineer",
  ],
  "Healthcare, Nursing & Clinical": [
    "Activities Director", "Anesthesia Technician", "Anesthesiologist", "Athletic Trainer",
    "Audiologist", "Behavioral Health Technician", "Cardiac Sonographer",
    "Cardiovascular Technologist", "Care Coordinator", "Caregiver",
    "Certified Medical Technologist", "Certified Nursing Assistant", "Charge Nurse",
    "Chiropractor", "Clinical Coordinator", "Clinical Data Manager",
    "Clinical Laboratory Scientist", "Clinical Nurse Coordinator", "Clinical Nurse Specialist",
    "Clinical Operations Manager", "Clinical Pharmacist", "Clinical Research Associate",
    "Clinical Research Coordinator", "Clinical Social Worker", "Clinical Trial Manager",
    "Credentialing Specialist", "CT Technologist", "Dental Assistant", "Dental Hygienist",
    "Dental Office Manager", "Dentist", "Dialysis Technician", "Dietitian",
    "Direct Support Professional", "Director of Nursing", "EKG Technician",
    "Emergency Medical Technician", "Emergency Room Nurse", "Endoscopy Technician",
    "Genetic Counselor", "Health Coach", "Health Information Technician",
    "Healthcare Administrator", "Histotechnologist", "Home Health Aide", "Hospice Nurse",
    "Hospitalist", "ICU Nurse", "Infection Control Practitioner", "Labor and Delivery Nurse",
    "Licensed Practical Nurse", "Mammography Technologist", "Marriage and Family Therapist",
    "Massage Therapist", "Medical Assistant", "Medical Biller", "Medical Coder",
    "Medical Director", "Medical Laboratory Technician", "Medical Office Manager",
    "Medical Receptionist", "Medical Scribe", "Mental Health Counselor", "MRI Technologist",
    "Nuclear Medicine Technologist", "Nurse Anesthetist", "Nurse Case Manager", "Nurse Educator",
    "Nurse Manager", "Nurse Midwife", "Nurse Practitioner", "Nursing Supervisor",
    "Occupational Therapist", "Occupational Therapy Assistant", "Oncology Nurse",
    "Operating Room Nurse", "Optical Lab Technician", "Optician", "Optometrist", "Oral Surgeon",
    "Orthodontist", "Orthopedic Technician", "Paramedic", "Patient Access Representative",
    "Patient Care Assistant", "Patient Care Coordinator", "Patient Care Technician",
    "Patient Navigator", "Patient Services Coordinator", "Pediatric Nurse", "Perfusionist",
    "Personal Care Aide", "Pharmacist", "Pharmacy Buyer", "Pharmacy Technician", "Phlebotomist",
    "Physical Therapist", "Physical Therapist Assistant", "Physician", "Physician Assistant",
    "Podiatrist", "Polysomnographic Technologist", "Practice Manager", "Psychiatrist",
    "Psychologist", "Radiation Therapist", "Radiologic Technologist", "Recreational Therapist",
    "Registered Nurse", "Regulatory Affairs Specialist", "Respiratory Therapist",
    "Revenue Cycle Specialist", "Scheduling Coordinator", "School Nurse",
    "Speech Language Pathologist", "Speech Therapist", "Sterile Processing Technician",
    "Substance Abuse Counselor", "Surgical Assistant", "Surgical Technician",
    "Surgical Technologist", "Telemetry Nurse", "Travel Nurse", "Ultrasound Technologist",
    "Unit Secretary", "Utilization Review Nurse", "Vascular Technologist", "Veterinary Assistant",
    "Veterinary Technician", "Wound Care Nurse",
  ],
  "Biotech, Pharma & Life Sciences": [
    "Analytical Chemist", "Assay Development Scientist", "Bioanalytical Scientist",
    "Bioinformatics Scientist", "Bioprocess Engineer", "Biostatistician",
    "Biotech Sales Specialist", "Cell Culture Associate", "Clinical Pharmacologist",
    "Clinical Project Manager", "Clinical Quality Auditor", "Compliance Specialist",
    "Computational Biologist", "Document Control Specialist", "Downstream Process Engineer",
    "Drug Safety Associate", "Field Application Scientist", "Flow Cytometry Specialist",
    "Formulation Scientist", "Genomics Scientist", "GMP Quality Specialist", "Immunologist",
    "Lab Manager", "Laboratory Technician", "Manufacturing Associate", "Manufacturing Operator",
    "Manufacturing Sciences and Technology Engineer", "Medical Affairs Manager",
    "Medical Science Liaison", "Medical Writer", "Medicinal Chemist", "Microbiologist",
    "Molecular Biologist", "Pharmaceutical Sales Representative", "Pharmacokineticist",
    "Pharmacologist", "Pharmacometrician", "Pharmacovigilance Specialist",
    "Principal Investigator", "Process Development Scientist", "Quality Assurance Associate",
    "Quality Control Analyst", "Quality Control Microbiologist", "Quality Systems Specialist",
    "Regulatory Affairs Associate", "Regulatory Affairs Manager", "Research Associate",
    "Research Technician", "Scientist", "Stability Coordinator", "Statistical Programmer",
    "Toxicologist", "Upstream Process Engineer", "Validation Specialist", "Vivarium Technician",
  ],
  "Finance, Accounting & Banking": [
    "Accounting Clerk", "Accounting Manager", "Accounting Specialist", "Accounts Payable Manager",
    "Accounts Payable Specialist", "Accounts Receivable Manager", "Accounts Receivable Specialist",
    "Actuarial Analyst", "Actuary", "AML Analyst", "Asset Management Analyst",
    "Assistant Controller", "Audit Manager", "Audit Senior", "Auditor", "Bank Teller",
    "Billing Coordinator", "Billing Manager", "Billing Specialist", "Bookkeeper", "Branch Manager",
    "Capital Markets Analyst", "Chief Financial Officer", "Collections Specialist",
    "Commercial Banker", "Commercial Loan Officer", "Compliance Analyst", "Compliance Officer",
    "Corporate Controller", "Corporate Development Manager", "Cost Accountant", "Credit Analyst",
    "Credit Officer", "Credit Risk Analyst", "Deal Analyst", "Derivatives Analyst",
    "Equity Research Analyst", "Finance Director", "Financial Advisor", "Financial Controller",
    "Financial Operations Analyst", "Financial Planning and Analysis Manager",
    "Financial Reporting Manager", "Financial Systems Analyst", "Fixed Income Analyst",
    "FP&A Analyst", "FP&A Manager", "Fraud Analyst", "Fund Accountant", "Grant Accountant",
    "Hedge Fund Analyst", "Internal Auditor", "Investment Advisor", "Investment Analyst",
    "Investment Banking Analyst", "Investment Banking Associate", "Investor Relations Manager",
    "KYC Analyst", "Loan Officer", "Loan Processor", "Loan Servicing Specialist",
    "Mergers and Acquisitions Analyst", "Mortgage Banker", "Mortgage Closer",
    "Mortgage Loan Officer", "Mortgage Processor", "Mortgage Underwriter", "Payroll Manager",
    "Payroll Specialist", "Personal Banker", "Portfolio Manager", "Pricing Analyst",
    "Private Equity Analyst", "Procurement Buyer", "Property Accountant", "Quantitative Analyst",
    "Reconciliation Analyst", "Relationship Manager", "Revenue Accountant", "Revenue Analyst",
    "Risk Manager", "Securities Analyst", "Senior Accountant", "Settlements Analyst",
    "Staff Accountant", "Tax Accountant", "Tax Analyst", "Tax Associate", "Tax Director",
    "Tax Manager", "Tax Preparer", "Trade Support Analyst", "Trader", "Treasury Analyst",
    "Treasury Manager", "Underwriter", "Venture Capital Analyst", "VP of Finance",
    "Wealth Management Advisor",
  ],
  "Legal, Compliance & Risk": [
    "AML Investigator", "Anti-Money Laundering Analyst", "Associate Attorney",
    "Associate General Counsel", "Attorney", "BSA Analyst", "Commercial Contracts Manager",
    "Commercial Counsel", "Compliance Coordinator", "Compliance Counsel", "Compliance Manager",
    "Contract Specialist", "Contracts Manager", "Corporate Counsel", "Corporate Paralegal",
    "Court Reporter", "Data Privacy Manager", "Deputy General Counsel", "Discovery Analyst",
    "Document Review Attorney", "eDiscovery Specialist", "Employment Counsel",
    "Enterprise Risk Manager", "Ethics and Compliance Manager", "Export Compliance Manager",
    "Financial Crimes Investigator", "Fraud Investigator", "General Counsel",
    "Governance Risk and Compliance Analyst", "Intellectual Property Counsel",
    "Know Your Customer Analyst", "Legal Assistant", "Legal Counsel", "Legal Counsel Privacy",
    "Legal Operations Manager", "Legal Secretary", "Litigation Attorney", "Litigation Counsel",
    "Litigation Paralegal", "Operational Risk Manager", "Paralegal", "Patent Agent",
    "Patent Attorney", "Policy Analyst", "Privacy Analyst", "Privacy Counsel", "Product Counsel",
    "Regulatory Counsel", "Risk Analyst", "Sanctions Analyst", "Third Party Risk Analyst",
    "Title Agent", "Trade Compliance Specialist", "Trademark Attorney", "Trust and Safety Analyst",
    "Trust and Safety Specialist", "Vendor Risk Manager",
  ],
  "Sales & Business Development": [
    "Account Coordinator", "Account Director", "Account Representative", "Account Strategist",
    "Alliance Manager", "Business Development Director", "Business Development Executive",
    "Business Development Manager", "Channel Partner Manager", "Channel Sales Manager",
    "Chief Revenue Officer", "Commercial Account Manager", "Customer Success Representative",
    "Enterprise Account Executive", "Field Sales Representative", "Inside Sales Manager",
    "Inside Sales Representative", "Key Account Manager", "Lead Generation Specialist",
    "Medical Device Sales Representative", "National Account Manager",
    "Outside Sales Representative", "Partnerships Manager", "Pre-Sales Consultant",
    "Regional Account Manager", "Regional Sales Director", "Regional Sales Manager",
    "Renewals Manager", "Retail Sales Associate", "Revenue Operations Manager",
    "Sales Account Manager", "Sales Analyst", "Sales Associate", "Sales Coordinator",
    "Sales Director", "Sales Enablement Manager", "Sales Manager", "Sales Operations Analyst",
    "Sales Operations Coordinator", "Sales Operations Manager", "Sales Representative",
    "Sales Specialist", "Sales Support Specialist", "Sales Trainer", "Solutions Consultant",
    "Strategic Account Manager", "Telesales Representative", "Territory Manager",
    "Territory Sales Manager", "VP of Sales",
  ],
  "Marketing, Communications & PR": [
    "Account Planner", "Affiliate Marketing Manager", "Brand Manager", "Brand Marketing Manager",
    "Brand Strategist", "Communications Coordinator", "Communications Director",
    "Communications Manager", "Community Manager", "Content Manager", "Content Marketing Manager",
    "Content Marketing Specialist", "Conversion Rate Optimization Specialist", "Copywriter",
    "Corporate Communications Manager", "Creative Director", "Customer Marketing Manager",
    "Demand Generation Specialist", "Digital Marketing Manager", "Digital Marketing Specialist",
    "Email Marketing Manager", "Email Marketing Specialist", "Event Marketing Manager",
    "Field Marketing Manager", "Graphic Designer", "Growth Marketing Specialist",
    "Influencer Marketing Manager", "Integrated Marketing Manager",
    "Internal Communications Manager", "Lifecycle Marketing Manager", "Market Research Analyst",
    "Marketing Analyst", "Marketing Assistant", "Marketing Automation Specialist",
    "Marketing Communications Manager", "Marketing Coordinator", "Marketing Director",
    "Marketing Events Coordinator", "Marketing Operations Manager",
    "Marketing Operations Specialist", "Marketing Specialist", "Media Buyer", "Media Planner",
    "Paid Media Manager", "Paid Search Specialist", "Partner Marketing Manager",
    "Performance Marketing Manager", "PR Account Executive", "Product Marketing Manager",
    "Product Marketing Specialist", "Public Relations Manager", "Public Relations Specialist",
    "SEO Manager", "Social Media Coordinator", "Social Media Manager", "Social Media Specialist",
    "Social Media Strategist", "Trade Marketing Manager", "Web Content Manager", "Webmaster",
  ],
  "Human Resources, Recruiting & People": [
    "Benefits Administrator", "Benefits Manager", "Benefits Specialist", "Campus Recruiter",
    "Chief People Officer", "Compensation Analyst", "Compensation and Benefits Manager",
    "Diversity and Inclusion Manager", "Employee Experience Manager", "Employee Relations Manager",
    "Employee Relations Specialist", "Executive Recruiter", "HR Assistant", "HR Business Partner",
    "HR Coordinator", "HR Operations Manager", "HR Specialist", "HRIS Analyst", "HRIS Manager",
    "Human Resources Business Partner", "Human Resources Director", "Human Resources Generalist",
    "Instructional Designer", "Labor Relations Specialist", "Learning and Development Manager",
    "Learning and Development Specialist", "Onboarding Specialist",
    "Organizational Development Manager", "Payroll Administrator", "Payroll Coordinator",
    "People Analytics Manager", "People Business Partner", "People Operations Coordinator",
    "People Partner", "Recruiting Coordinator", "Recruiting Manager",
    "Recruiting Operations Manager", "Recruitment Coordinator", "Sourcer", "Staffing Coordinator",
    "Staffing Manager", "Talent Acquisition Coordinator", "Talent Acquisition Manager",
    "Talent Acquisition Partner", "Talent Acquisition Specialist", "Talent Development Manager",
    "Talent Management Specialist", "Talent Partner", "Talent Sourcer", "Total Rewards Manager",
    "Training Coordinator", "Workforce Planning Analyst",
  ],
  "Operations, Administration & Facilities": [
    "Administrative Assistant", "Administrative Coordinator", "Administrative Services Manager",
    "Building Engineer", "Chief Operating Officer", "Custodian", "Data Entry Clerk", "EHS Manager",
    "Environmental Health and Safety Specialist", "Executive Assistant", "Facilities Coordinator",
    "Facilities Manager", "Facilities Technician", "Front Desk Coordinator",
    "Janitorial Supervisor", "Mailroom Clerk", "Management Consultant", "Office Administrator",
    "Office Coordinator", "Office Manager", "Operations Associate", "Operations Director",
    "Operations Engineer", "Operations Specialist", "Personal Assistant",
    "Process Improvement Manager", "Project Coordinator", "Property Manager",
    "Real Estate Manager", "Receptionist", "Security Manager", "Security Officer", "Space Planner",
    "Strategy Analyst", "Strategy Manager", "Virtual Assistant", "VP of Operations",
    "Workplace Coordinator", "Workplace Experience Manager",
  ],
  "Customer Service & Support": [
    "Bilingual Customer Service Representative", "Call Center Representative",
    "Client Services Manager", "Client Support Specialist", "Contact Center Agent",
    "Customer Advocacy Manager", "Customer Care Representative", "Customer Experience Manager",
    "Customer Experience Specialist", "Customer Insights Analyst",
    "Customer Onboarding Specialist", "Customer Service Coordinator", "Customer Service Director",
    "Customer Service Manager", "Customer Solutions Engineer",
    "Customer Success Operations Manager", "Customer Success Specialist",
    "Customer Support Associate", "Customer Support Manager", "Escalation Specialist",
    "Help Desk Technician", "Implementation Specialist", "Member Services Representative",
    "Patient Support Specialist", "Service Desk Analyst", "Support Engineer",
    "Support Operations Manager",
  ],
  "Construction, Architecture & Real Estate": [
    "Acquisitions Analyst", "Appraiser", "Architect", "Architectural Designer",
    "Architectural Drafter", "Asset Manager", "Assistant Project Manager",
    "Assistant Property Manager", "BIM Coordinator", "BIM Manager", "Building Inspector",
    "Carpenter", "Commercial Real Estate Broker", "Concrete Finisher", "Concrete Form Setter",
    "Concrete Laborer", "Construction Accountant", "Construction Administrator",
    "Construction Coordinator", "Construction Estimator", "Construction Foreman",
    "Construction Inspector", "Construction Laborer", "Construction Project Coordinator",
    "Construction Project Manager", "Construction Safety Officer", "Cost Estimator",
    "Crane Operator", "Demolition Worker", "Design Architect", "Development Manager",
    "Drywall Installer", "Electrician", "Entitlements Manager", "Escrow Officer",
    "Excavator Operator", "Field Safety Coordinator", "Field Superintendent", "Flooring Installer",
    "Foreman", "General Laborer", "General Superintendent", "Glazier", "Heavy Equipment Operator",
    "Heavy Equipment Technician", "HVAC Technician", "Insulation Installer", "Interior Designer",
    "Ironworker", "Landscape Architect", "Leasing Agent", "Leasing Consultant", "Leasing Manager",
    "MEP Coordinator", "MEP Engineer", "Mortgage Broker", "Mortgage Loan Processor",
    "Permit Coordinator", "Pipelayer", "Plumber", "Preconstruction Manager", "Project Architect",
    "Project Controls Specialist", "Project Executive", "Project Scheduler",
    "Property Administrator", "Quality Control Manager", "Quantity Surveyor", "Real Estate Agent",
    "Real Estate Analyst", "Real Estate Appraiser", "Real Estate Broker",
    "Real Estate Development Manager", "Real Estate Transaction Coordinator", "Realtor",
    "Rebar Worker", "Roofer", "Safety Manager", "Scaffolder", "Scheduler", "Sheet Metal Installer",
    "Site Manager", "Superintendent", "Surveyor", "Tile Setter", "Title Examiner",
    "Underwriting Analyst", "Urban Planner",
  ],
  "Energy, Oil & Gas, Utilities & Renewables": [
    "Battery Engineer", "Carbon Analyst", "Completions Engineer", "Control Room Operator",
    "Derrickhand", "Distribution Engineer", "Drilling Engineer", "Drilling Supervisor",
    "Energy Analyst", "Energy Consultant", "Energy Engineer", "Energy Project Developer",
    "Energy Storage Engineer", "Energy Trader", "Environmental Specialist", "Gas Controller",
    "Gas Technician", "Geologist", "Geophysicist", "Grid Operator", "Health and Safety Specialist",
    "HSE Manager", "Land Manager", "Landman", "Lineman", "Mechanical Integrity Engineer",
    "Meter Technician", "Mining Engineer", "Mud Logger", "Nuclear Engineer", "Petroleum Engineer",
    "Petrophysicist", "Pipeline Engineer", "Plant Operator", "Power Lineman",
    "Power Plant Operator", "Power Trader", "Process Operator", "Pumper", "Reactor Operator",
    "Renewable Energy Engineer", "Reservoir Engineer", "Reservoir Geologist", "Rig Operator",
    "Roustabout", "SCADA Engineer", "Solar Engineer", "Solar Installer", "Solar Technician",
    "Subsea Engineer", "Substation Engineer", "Sustainability Manager", "Tank Farm Operator",
    "Transmission Engineer", "Utility Locator", "Utility Worker", "Water Treatment Operator",
    "Wind Turbine Engineer", "Wind Turbine Technician", "Wireline Operator",
  ],
  "Retail, E-commerce & Consumer Goods": [
    "Allocation Analyst", "Assistant Buyer", "Assistant Store Manager", "Brand Ambassador",
    "Buyer Planner", "Cashier", "Category Analyst", "Customer Experience Associate",
    "Customer Service Associate", "Demand Planning Analyst", "Department Manager",
    "District Manager", "E-commerce Manager", "E-commerce Specialist", "Inventory Control Manager",
    "Inventory Specialist", "Key Holder", "Loss Prevention Manager", "Loss Prevention Officer",
    "Merchandise Coordinator", "Merchandise Planner", "Merchandiser", "Merchandising Manager",
    "Personal Shopper", "Planogram Specialist", "Pricing Manager", "Product Photographer",
    "Receiving Associate", "Regional Manager", "Replenishment Analyst", "Retail Buyer",
    "Retail Operations Manager", "Retail Store Manager", "Sales Floor Associate", "Sales Lead",
    "Shift Lead", "Stock Associate", "Stocker", "Store Associate", "Store Manager",
    "Visual Merchandiser",
  ],
  "Education, Training & Academia": [
    "Academic Advisor", "Academic Coordinator", "Adjunct Faculty", "Admissions Counselor",
    "Admissions Officer", "Admissions Representative", "Assistant Principal",
    "Behavior Technician", "Bus Aide", "Camp Counselor", "Career Counselor", "Childcare Worker",
    "Coach", "Corporate Trainer", "Curriculum Coordinator", "Curriculum Developer",
    "Curriculum Specialist", "Daycare Teacher", "Dean of Students", "Department Chair",
    "Education Consultant", "Education Outreach Coordinator", "Education Program Coordinator",
    "Education Program Manager", "Education Specialist", "English Teacher",
    "Enrollment Specialist", "ESL Teacher", "Faculty Coordinator", "Financial Aid Advisor",
    "Guidance Counselor", "Instructional Aide", "Instructional Coach", "Instructor",
    "Learning Experience Designer", "Learning Management System Administrator", "Lecturer",
    "Librarian", "Library Assistant", "Math Teacher", "Online Course Developer",
    "Paraprofessional", "Postdoctoral Researcher", "Preschool Teacher", "Principal", "Professor",
    "Professor of Practice", "Registrar", "Research Assistant", "School Counselor",
    "School Psychologist", "Science Teacher", "Special Education Teacher", "Student Advisor",
    "Student Services Coordinator", "Substitute Teacher", "Teacher", "Teaching Assistant",
    "Teaching Fellow", "Test Proctor", "Training Specialist", "Tutor",
  ],
  "Hospitality, Food Service & Travel": [
    "Assistant Restaurant Manager", "Banquet Captain", "Banquet Manager", "Banquet Server",
    "Bar Back", "Bar Manager", "Barista", "Bartender", "Bellhop", "Busser", "Cafeteria Manager",
    "Cafeteria Worker", "Cage Cashier", "Casino Dealer", "Catering Coordinator",
    "Catering Director", "Catering Manager", "Catering Sales Manager", "Catering Server",
    "Concierge", "Cook", "Cruise Director", "Culinary Director", "Director of Rooms",
    "Director of Sales", "Dishwasher", "Doorman", "Event Coordinator", "Event Manager",
    "Executive Chef", "Executive Housekeeper", "Flight Attendant", "Food and Beverage Manager",
    "Food Runner", "Food Safety Manager", "Front Desk Agent", "Front Desk Supervisor",
    "Front Office Manager", "Guest Relations Manager", "Guest Services Manager",
    "Hospitality Recruiter", "Host", "Hostess", "Hotel General Manager", "Hotel Manager",
    "Housekeeping Manager", "Housekeeping Supervisor", "Kitchen Manager", "Line Cook",
    "Maintenance Engineer Hotel", "Night Auditor", "Pastry Chef", "Pit Boss", "Prep Cook",
    "Quality Assurance Manager", "Reservations Agent", "Reservations Manager",
    "Restaurant General Manager", "Restaurant Manager", "Revenue Manager", "Room Attendant",
    "Sales Coordinator Hospitality", "Server", "Slot Technician", "Sommelier", "Sous Chef",
    "Spa Manager", "Tour Guide", "Travel Agent", "Travel Consultant", "Valet Attendant", "Waiter",
  ],
  "Media, Creative, Content & Design (non-UX)": [
    "3D Artist", "Animator", "Art Director", "Assistant Editor", "Audio Engineer",
    "Audio Visual Technician", "Brand Designer", "Broadcast Engineer", "Broadcast Technician",
    "Camera Operator", "Casting Director", "Colorist", "Content Creator", "Content Producer",
    "Copy Editor", "Creative Operations Manager", "Creative Producer", "Creative Project Manager",
    "Creative Strategist", "Design Manager", "Designer", "Director of Photography", "Editor",
    "Editorial Director", "Email Designer", "Gaffer", "Grip", "Illustrator", "Industrial Designer",
    "Journalist", "Managing Editor", "Motion Designer", "Motion Graphics Designer",
    "Multimedia Producer", "News Anchor", "News Producer", "Packaging Designer", "Photo Editor",
    "Photographer", "Podcast Producer", "Presentation Designer", "Print Designer", "Producer",
    "Production Artist", "Production Assistant", "Production Coordinator", "Production Designer",
    "Reporter", "Set Designer", "Sound Designer", "Staff Writer", "Studio Manager", "UX Writer",
    "Video Editor", "Video Producer", "Videographer", "Visual Designer", "Voice Actor",
    "Web Designer",
  ],
  "Science, Research & Laboratory": [
    "Analytical Scientist", "Animal Care Technician", "Astronomer", "Biochemist", "Biologist",
    "Chemist", "Cytotechnologist", "Director of Research", "Epidemiologist", "Forensic Scientist",
    "Geneticist", "Hydrologist", "Lab Analyst", "Lab Assistant", "Lab Technician",
    "Laboratory Director", "Laboratory Manager", "Marine Biologist", "Materials Scientist",
    "Medical Laboratory Scientist", "Medical Technologist", "Meteorologist",
    "Metrology Technician", "Organic Chemist", "Physicist", "Quality Control Chemist",
    "Quality Control Microbiologist Technician", "Quality Control Scientist",
    "Research and Development Manager", "Research Engineer", "Scientific Director",
    "Senior Scientist", "Study Director", "Validation Technician", "Wildlife Biologist",
  ],
  "Automotive & Mobility": [
    "ADAS Engineer", "Auto Body Technician", "Automotive Engineer", "Automotive Painter",
    "Automotive Salesperson", "Automotive Technician", "Autonomous Vehicle Engineer",
    "Battery Cell Engineer", "Body Engineer", "Calibration Engineer",
    "Charging Infrastructure Manager", "Chassis Engineer", "Collision Repair Technician",
    "Crash Safety Engineer", "Dealership General Manager", "Diagnostic Technician",
    "Durability Engineer", "Electric Vehicle Engineer", "Electrical Systems Engineer",
    "EV Charging Technician", "Finance and Insurance Manager", "Functional Safety Engineer",
    "Homologation Engineer", "Lube Technician", "Master Technician", "Mechanic", "NVH Engineer",
    "Parts Manager", "Perception Engineer", "Powertrain Engineer", "Quick Lube Technician",
    "Sales Consultant", "Service Advisor", "Service Technician", "Service Writer",
    "Tire Technician", "Used Car Manager", "Vehicle Dynamics Engineer", "Vehicle Engineer",
    "Vehicle Integration Engineer", "Vehicle Operations Manager", "Vehicle Program Manager",
    "Vehicle Test Engineer", "Vehicle Test Technician", "Wire Harness Engineer",
  ],
  "Agriculture, Food Production & Environmental": [
    "Agricultural Engineer", "Agricultural Sales Representative", "Agricultural Technician",
    "Agronomist", "Animal Nutritionist", "Beekeeper", "Beekeeping Technician", "Butcher",
    "Commodity Trader", "Conservation Scientist", "Crop Consultant", "Crop Insurance Adjuster",
    "Crop Scientist", "Dairy Manager", "Ecologist", "Environmental Compliance Specialist",
    "Environmental Scientist", "Equipment Operator Agriculture", "Farm Manager", "Farm Worker",
    "Farmhand", "Field Agronomist", "Fishery Manager", "Food Production Manager", "Food Scientist",
    "Food Technologist", "Forester", "Grain Elevator Operator", "Grain Merchandiser",
    "Greenhouse Manager", "Herdsman", "Horticulturist", "Irrigation Technician",
    "Livestock Manager", "Meat Cutter", "Plant Breeder", "Precision Agriculture Specialist",
    "Product Development Scientist", "Quality Control Technician", "R&D Food Scientist",
    "Ranch Manager", "Sanitation Manager", "Sensory Scientist", "Soil Scientist",
    "Tractor Operator", "Veterinarian", "Viticulturist", "Wastewater Treatment Operator",
  ],
  "Government, Public Sector & Nonprofit": [
    "Annual Giving Manager", "Budget Analyst", "Building Code Inspector", "Case Manager",
    "Caseworker", "City Planner", "Code Enforcement Officer", "Community Organizer",
    "Community Outreach Coordinator", "Constituent Services Representative",
    "Contract Administrator Government", "Correctional Officer", "Deputy Sheriff",
    "Detention Officer", "Development Coordinator", "Development Director",
    "Donor Relations Manager", "Eligibility Specialist", "Emergency Management Specialist",
    "Executive Director", "Firefighter", "Foreign Service Officer", "Foundation Relations Manager",
    "Fundraising Manager", "Government Relations Manager", "Grant Writer", "Grants Administrator",
    "Grants Manager", "Health Educator", "Housing Specialist", "Intake Specialist",
    "Legislative Aide", "Legislative Assistant", "Major Gifts Officer", "Management Analyst",
    "Membership Coordinator", "Membership Manager", "Monitoring and Evaluation Officer",
    "Outreach Specialist", "Park Ranger", "Police Officer", "Policy Advisor", "Probation Officer",
    "Procurement Officer", "Program Coordinator", "Program Evaluator", "Program Officer",
    "Public Affairs Specialist", "Public Health Nurse", "Public Health Specialist",
    "Public Information Officer", "Records Manager", "Social Services Specialist", "Social Worker",
    "Tax Examiner", "Vocational Rehabilitation Counselor", "Volunteer Coordinator",
    "Youth Counselor",
  ],
  "Insurance & Actuarial": [
    "Account Coordinator Insurance", "Account Manager Insurance", "Actuarial Associate",
    "Auto Damage Appraiser", "Benefits Analyst", "Benefits Consultant", "Benefits Coordinator",
    "Casualty Adjuster", "Catastrophe Adjuster", "Catastrophe Modeler", "Catastrophe Risk Analyst",
    "Claims Adjuster", "Claims Examiner", "Claims Manager", "Claims Processor",
    "Claims Representative", "Claims Specialist", "Commercial Lines Underwriter",
    "Disability Claims Examiner", "Field Adjuster", "Insurance Account Manager", "Insurance Agent",
    "Insurance Broker", "Insurance Customer Service Representative",
    "Insurance Operations Manager", "Insurance Sales Representative", "Insurance Underwriter",
    "Insurance Verification Specialist", "Loss Control Consultant", "Loss Control Specialist",
    "Personal Lines Underwriter", "Policy Administrator", "Policy Services Representative",
    "Premium Auditor", "Pricing Actuary", "Property Adjuster", "Reinsurance Analyst",
    "Reserving Actuary", "Risk Engineer", "Subrogation Specialist", "Surety Underwriter",
    "Underwriting Assistant", "Underwriting Manager", "Workers Compensation Adjuster",
  ],
  "Transportation, Aviation Operations & Maritime": [
    "Able Seaman", "Air Traffic Controller", "Aircraft Dispatcher", "Aircraft Inspector",
    "Aircraft Line Service Technician", "Airline Customer Service Agent",
    "Airport Operations Manager", "Aviation Inspector", "Aviation Maintenance Planner",
    "Aviation Mechanic", "Aviation Safety Officer", "Baggage Handler", "Bus Driver", "Cargo Agent",
    "Carrier Sales Representative", "CDL Driver", "Courier", "Crane Technician", "Crew Scheduler",
    "Customer Service Agent", "Deck Officer", "Deckhand", "Delivery Driver", "Diesel Mechanic",
    "Dock Supervisor", "DOT Compliance Manager", "Driver Helper", "Driver Manager",
    "First Officer", "Fleet Maintenance Technician", "Flight Dispatcher", "Flight Engineer",
    "Flight Operations Manager", "Freight Coordinator", "Freight Forwarder", "Gate Agent",
    "Ground Operations Agent", "Line Maintenance Technician", "Load Planner", "Local Truck Driver",
    "Locomotive Engineer", "Logistics Account Manager", "Longshoreman", "Marine Engineer",
    "Marine Mechanic", "Marine Surveyor", "Maritime Operations Coordinator", "Mate", "Oiler",
    "Over the Road Driver", "Owner Operator", "Pilot", "Port Captain", "Port Operations Manager",
    "Railroad Conductor", "Ramp Agent", "Route Manager", "Safety Manager Transportation",
    "Ship Captain", "Shuttle Driver", "Stevedore", "Terminal Operations Manager",
    "Tractor Trailer Driver", "Transportation Planner", "Truck Driver", "Tugboat Operator",
    "Vessel Master", "Vessel Operations Manager", "Yard Jockey", "Yard Manager",
  ],
  "Skilled Trades & Field Service": [
    "Appliance Repair Technician", "Apprentice Technician", "Auto Glass Technician",
    "Automation Technician", "Boiler Operator", "Building Maintenance Technician", "Cabinet Maker",
    "Cable Technician", "Diesel Technician", "Elevator Mechanic", "Equipment Operator",
    "Fiber Optic Technician", "Field Operations Manager", "Field Service Director",
    "Field Service Manager", "Fire Sprinkler Fitter", "Forklift Mechanic",
    "Garage Door Technician", "Glass Installer", "Groundskeeper", "Heavy Equipment Mechanic",
    "HVAC Installer", "HVAC Service Technician", "Industrial Electrician",
    "Installation Technician", "Journeyman Electrician", "Landscaper", "Locksmith",
    "Low Voltage Technician", "Maintenance Mechanic", "Maintenance Supervisor",
    "Maintenance Worker", "Mason", "Mechatronics Technician", "Millwright", "Painter",
    "Pest Control Technician", "Pipefitter", "Plumbing Technician", "Pool Technician",
    "Powerhouse Mechanic", "Quality Control Inspector", "Refrigeration Technician",
    "Robotics Technician", "Service Coordinator", "Service Manager", "Sheet Metal Worker",
    "Small Engine Mechanic", "Solar Sales Consultant", "Sprinkler Fitter", "Stationary Engineer",
    "Telecommunications Technician", "Telephone Technician", "Tree Trimmer", "Upholsterer",
    "Wind Energy Technician",
  ],
};

const ALL_ROLES = [...new Set(Object.values(ROLES_BY_INDUSTRY).flat())];

module.exports = { ROLES_BY_INDUSTRY, ALL_ROLES };
